// Step C.8 — the card a shared link becomes, fetched rather than described.
//
// `share-card.test.tsx` holds the colours and the words. It cannot say whether
// the image *exists*: the card is generated by a metadata route that reads two
// font files off disk, and every way that goes wrong produces a build that
// succeeds and a link that arrives bare.
//
// It went wrong twice while this step was written, and neither failure is
// visible anywhere but here:
//
// - the documented `fetch(new URL('./font.ttf', import.meta.url))` is rewritten
//   by webpack into `/_next/static/media/…`, which a server-side fetch cannot
//   parse. The route 500s and nothing else notices.
// - the English card lives at `/en/opengraph-image/card` because Next writes
//   the segment into the tag, and the locale proxy redirected that to the
//   unprefixed path — mangling the cache-busting query on the way.
//
// So the assertions are: the tag says something, it is per locale, and what it
// points at is a PNG of the right size served without a detour.
import { expect, test, type Page } from '@playwright/test';

/** What one page declares about its card. */
async function cardTags(page: Page, path: string) {
  await page.goto(path);

  const content = async (selector: string): Promise<string | null> =>
    page.locator(selector).getAttribute('content');

  return {
    image: await content('meta[property="og:image"]'),
    alt: await content('meta[property="og:image:alt"]'),
    width: await content('meta[property="og:image:width"]'),
    height: await content('meta[property="og:image:height"]'),
    type: await content('meta[property="og:image:type"]'),
    card: await content('meta[name="twitter:card"]'),
    twitterImage: await content('meta[name="twitter:image"]'),
    twitterAlt: await content('meta[name="twitter:image:alt"]'),
  };
}

/**
 * A PNG's own header, read from the bytes.
 *
 * The signature and the `IHDR` dimensions: eight bytes of magic, then a chunk
 * whose width and height are big-endian at offsets 16 and 20. `Content-Type` is
 * what a server says it sent; this is what it sent.
 */
function pngSize(bytes: Buffer): { png: boolean; width: number; height: number } {
  const signature = bytes.subarray(0, 8).toString('hex');
  return {
    png: signature === '89504e470d0a1a0a',
    width: bytes.readUInt32BE(16),
    height: bytes.readUInt32BE(20),
  };
}

test.describe('C.8 — the share card', () => {
  test('is declared, sized and described on the front door', async ({ page }) => {
    const tags = await cardTags(page, '/');

    expect(tags.image).toContain('/opengraph-image/');
    expect(tags.width).toBe('1200');
    expect(tags.height).toBe('630');
    expect(tags.type).toBe('image/png');

    // 1.91:1 at 1200 wide is what `summary_large_image` shows without cropping.
    // The image this replaced was 1024×1024, and every platform cut it.
    expect(tags.card).toBe('summary_large_image');

    // Twitter is not given its own image, so Next fills it from the Open Graph
    // one: the card is stated in a single place, and this is what says so.
    expect(tags.twitterImage).toBe(tags.image);

    // An alt is not decoration here. When the card is the whole of a shared
    // post, it is what a screen reader reads out.
    expect(tags.alt).toContain('WikiFake');
    expect(tags.twitterAlt).toBe(tags.alt);
  });

  test('is a different card, and a different alt, in French', async ({ page }) => {
    const english = await cardTags(page, '/');
    const french = await cardTags(page, '/fr');

    // The question is on the image, so the image is translated — which is the
    // whole reason it is generated rather than committed as a file.
    expect(french.image).not.toBe(english.image);
    expect(french.image).toContain('/fr/');
    expect(french.alt).not.toBe(english.alt);
    expect(french.alt).toContain('WikiFake');
  });

  test('answers with a 1200×630 PNG, with no redirect on the way', async ({
    page,
    request,
  }) => {
    for (const path of ['/', '/fr']) {
      const { image } = await cardTags(page, path);
      expect(image).not.toBeNull();

      // `maxRedirects: 0` is the assertion, not a setting: a scraper that does
      // not follow one gets nothing, and the locale proxy used to answer 307
      // here. A redirect fails this rather than being followed quietly.
      const answer = await request.get(image as string, { maxRedirects: 0 });
      expect({ path, status: answer.status() }).toEqual({ path, status: 200 });
      expect(answer.headers()['content-type']).toBe('image/png');

      const read = pngSize(await answer.body());
      expect({ path, ...read }).toEqual({ path, png: true, width: 1200, height: 630 });
    }
  });
});
